theme = "github_dark"

[editor]
cursorline = true
cursorcolumn = true
auto-pairs = true
shell = ["zsh", "-c"]
rulers = [80]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
